export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const LOAD_CUSTOMERS = "LOAD_CUSTOMERS";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_USER_ORDERS = "FETCH_USER_ORDERS";
export const FETCH_SCHEDULE = "FETCH_SCHEDULE";
export const FETCH_PROMOS = "FETCH_PROMOS";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const ADD_PROMO = "ADD_PROMO";
export const DEL_PROMO = "DEL_PROMO";
export const UPDATE_PROMO = "UPDATE_PROMO";
export const REFUND_ORDER = "REFUND_ORDER";
export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const UPDATE_ERROR = "UPDATE_ERROR";
export const FETCH_PENDING_ORDERS = "FETCH_PENDING_ORDERS";
export const FETCH_MORE_CUSTOMERS = "FETCH_MORE_CUSTOMERS";
export const FETCH_MORE_ORDERS = "FETCH_MORE_ORDERS";
export const FETCH_MORE_PROMOS = "FETCH_MORE_PROMOS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const SUBMIT_ORDER = "SUBMIT_ORDER";
export const GET_STORIES_LIST = "GET_STORIES_LIST";
export const GET_TAGS_LIST = "GET_TAGS_LIST";
export const SORT_STORIES_ON_DRAG = "SORT_STORIES_ON_DRAG";
// newsletter
export const LOAD_NEWS = "LOAD_NEWS";
export const FETCH_NEWS = "FETCH_NEWS";








