export const STRIPE_ERROR = "STRIPE_ERROR";
export const STRIPE_CUSTOMER_AND_SETUP_INTENT = "STRIPE_CUSTOMER_AND_SETUP_INTENT";
export const CREATE_PAYMENT_METHOD = "CREATE_PAYMENT_METHOD";
export const GET_PAYMENT_METHODS = "GET_PAYMENT_METHODS";