export const FREELANCERSKILLS_ERROR = "FREELANCERSKILLS_ERROR";
export const GET_LIST_FREELANCERSKILLS = "GET_LIST_FREELANCERSKILLS";
export const GET_ALL_FREELANCERS = "GET_ALL_FREELANCERS";
export const GET_ALL_FREELANCERS_ERROR = "GET_ALL_FREELANCERS_ERROR";