
version: '1.0'
services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    image: unzipped-app
    env_file: ./.env
    ports:
      - 3000:3000
    volumes: 
      - ./src:/src
