export const ADD_CART_DATA = "ADD_CART_DATA";
export const DEL_CART_DATA = "DEL_CART_DATA";
export const USER_SELECTED_LOCATION = "USER_SELECTED_LOCATION";
export const DEFAULT_LOCATION = "DEFAULT_LOCATION";
export const SELECTED_DATE = "SELECTED_DATE";
export const SELECTED_TIME = "SELECTED_TIME";
export const AVAILABLE_TIMES = "AVAILABLE_TIMES";
export const APP_SCREEN = 'APP_SCREEN';
export const CLEAR_CART = 'CLEAR_CART';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const ORDER_DETAILS = 'ORDER_DETAILS';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const CONFIRM_PROMO = 'CONFIRM_PROMO';
export const PROMO_NOT_VALID = 'PROMO_NOT_VALID';
export const ORDER_HISTORY = 'ORDER_HISTORY';
export const RESET_PROMO = 'RESET_PROMO';
export const SET_TOTAL = 'SET_TOTAL';
export const RESET_TOTAL = 'RESET_TOTAL';
export const RESET_ORDER = 'RESET_ORDER';
export const GET_GARAGES = 'GET_GARAGES';
export const LOAD_MORE_GARAGES = 'LOAD_MORE_GARAGES';
export const CUSTOM_LOCATION = 'CUSTOM_LOCATION';
export const SET_HOTEL = 'SET_HOTEL';


