// Departments
export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT'
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'
export const GET_DEPARTMENT_BY_ID = 'GET_DEPARTMENT_BY_ID'
export const SELECT_DEPARTMENT = 'SELECT_DEPARTMENT'
export const DEPARTMENT_ERROR = 'DEPARTMENT_ERROR'

export const LOAD_STATE = 'LOAD_STATE'
export const SUCCESS = 'SUCCESS'

export const UPDATE_DEPARTMENT_FORM = 'UPDATE_DEPARTMENT_FORM'
export const RESET_DEPARTMENT_FORM = 'RESET_DEPARTMENT_FORM'
