// Departments
export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT'
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'
export const GET_DEPARTMENT_BY_ID = 'GET_DEPARTMENT_BY_ID'
export const SELECT_DEPARTMENT = 'SELECT_DEPARTMENT'
export const DEPARTMENT_ERROR = 'DEPARTMENT_ERROR'

export const LOAD_STATE = 'LOAD_STATE'
export const SUCCESS = 'SUCCESS'

export const UPDATE_DEPARTMENT_FORM = 'UPDATE_DEPARTMENT_FORM'
export const RESET_DEPARTMENT_FORM = 'RESET_DEPARTMENT_FORM'
export const UPDATE_DEPARTMENT_INFO = 'UPDATE_DEPARTMENT_INFO'
export const UPDATE_TASK_STATUS_ON_DRAG = 'UPDATE_TASK_STATUS_ON_DRAG'
export const UPDATE_TASK_STATUS_ON_DRAG_ERROR = 'UPDATE_TASK_STATUS_ON_DRAG_ERROR'
export const DEPARTMEMT_INFO_SEARCH = 'DEPARTMEMT_INFO_SEARCH'
export const DEPARTMEMT_INFO_SEARCH_ERROR = 'DEPARTMEMT_INFO_SEARCH_ERROR'
export const IS_DEPARTMENT_EXISTS = 'IS_DEPARTMENT_EXISTS';
export const IS_DEPARTMENT_EXISTS_ERROR = 'IS_DEPARTMENT_EXISTS_ERROR';

