// Departments
export const CREATE_CONTRACT = 'CREATE_CONTRACT'
export const UPDATE_CONTRACT = 'UPDATE_CONTRACT'
export const DELETE_CONTRACT = 'DELETE_CONTRACT'
export const GET_CONTRACTS = 'GET_CONTRACT'
export const GET_CONTRACT_BY_ID = 'GET_CONTRACT_BY_ID'
export const CONTRACT_ERROR = 'CONTRACT_ERROR'

export const LOAD_STATE = 'LOAD_STATE'
export const SUCCESS = 'SUCCESS'
