// Departments
export const CREATE_SHOWCASE_PROJECT = 'CREATE_SHOWCASE_PROJECT'
export const UPDATE_SHOWCASE_PROJECT = 'UPDATE_SHOWCASE_PROJECT'
export const DELETE_SHOWCASE_PROJECT = 'DELETE_SHOWCASE_PROJECT'
export const GET_SHOWCASE_PROJECTS = 'GET_SHOWCASE_PROJECTS'
export const GET_SHOWCASE_PROJECT_BY_ID = 'GET_SHOWCASE_PROJECT_BY_ID'
export const SHOWCASE_PROJECT_ERROR = 'SHOWCASE_PROJECT_ERROR'
export const SHOW_SUCCESS_NOTIFICATION = 'SHOW_SUCCESS_NOTIFICATION'
export const HIDE_SUCCESS_NOTIFICATION = 'HIDE_SUCCESS_NOTIFICATION'

export const LOAD_STATE = 'LOAD_STATE'
export const SUCCESS = 'SUCCESS'
