export const CREATE_CALENDER_SETTING = "CREATE_CALENDER_SETTING";
export const CREATE_CALENDER_SETTING_SUCCESS = "CREATE_CALENDER_SETTING_SUCCESS";
export const CREATE_CALENDER_SETTING_ERROR = "CREATE_CALENDER_SETTING_ERROR";
export const CREATE_CALENDER_SETTING_LOADING = "CREATE_CALENDER_SETTING_LOADING";