// Departments
export const CREATE_PROJECT_APPLICATION = 'CREATE_PROJECT_APPLICATION'
export const UPDATE_PROJECT_APPLICATION = 'UPDATE_PROJECT_APPLICATION'
export const DELETE_PROJECT_APPLICATION = 'DELETE_PROJECT_APPLICATION'
export const GET_PROJECT_APPLICATIONS = 'GET_PROJECT_APPLICATIONS'
export const GET_PROJECT_APPLICATION_BY_ID = 'GET_PROJECT_APPLICATION_BY_ID'
export const PROJECT_APPLICATION_ERROR = 'PROJECT_APPLICATION_ERROR'

export const LOAD_STATE = 'LOAD_STATE'
export const SUCCESS = 'SUCCESS'
