export const FREELANCER_LOADING = "FREELANCER_LOADING";
export const GET_LIST_FREELANCERS = "GET_LIST_FREELANCERS";
export const GET_FREELANCER_BY_ID = "GET_FREELANCER_BY_ID";
export const RESET_SELECTED_FREELANCER = "RESET_SELECTED_FREELANCER";
export const FREELANCER_ERROR = "FREELANCER_ERROR";
