export const FREELANCER_LOADING = 'FREELANCER_LOADING'
export const GET_FREELANCER_BY_ID = 'GET_FREELANCER_BY_ID'
export const RESET_SELECTED_FREELANCER = 'RESET_SELECTED_FREELANCER'
export const FREELANCER_ERROR = 'FREELANCER_ERROR'
export const SETNAVBAR = 'SETNAVBAR'

export const GET_ALL_FREELANCERS = 'GET_ALL_FREELANCERS'
export const CREATE_USER_INVITATION_SUCCESS = 'CREATE_USER_INVITATION_SUCCESS'
export const CREATE_USER_INVITATION_ERROR = 'CREATE_USER_INVITATION_ERROR'
