// Departments
export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT'
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'
export const GET_DEPARTMENT_BY_ID = 'GET_DEPARTMENT_BY_ID'
export const SELECT_DEPARTMENT = 'SELECT_DEPARTMENT'
export const DEPARTMENT_ERROR = 'DEPARTMENT_ERROR'

// Tags
export const CREATE_TAG = 'MODEL_LOADING'
export const UPDATE_TAG = 'UPDATE_TAG'
export const GET_TAGS = 'GET_TAGS'
export const DELETE_TAG = 'DELETE_TAG'


// Stories
export const CREATE_STORY = 'CREATE_STORY'
export const UPDATE_STORY = 'UPDATE_STORY'
export const DELETE_STORY = 'DELETE_STORY'
export const GET_STORIES = 'GET_STORIES'
export const UPDATE_CREATE_STORY = 'UPDATE_CREATE_STORY'
export const SORT_STORIES_ON_DRAG = 'SORT_STORIES_ON_DRAG'
export const REORDER_STORIES = 'REORDER_STORIES'
export const ADD_COMMENT_TO_STORY = 'ADD_COMMENT_TO_STORY'
export const REMOVE_COMMENT_FROM_STORY = 'REMOVE_COMMENT_FROM_STORY'

// Business
export const UPDATE_BUSINESS_FORM = 'UPDATE_BUSINESS_FORM'
export const CREATE_BUSINESS = 'CREATE_BUSINESS'
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS'
export const DELETE_BUSINESS = 'DELETE_BUSINESS'
export const GET_BUSINESSES = 'GET_BUSINESSES'
export const SELECT_BUSINESS = 'SELECT_BUSINESS'
export const RESET_BUSINESS_FORM = 'RESET_BUSINESS_FORM'
export const GET_PROJECT_LIST = 'GET_PROJECT_LIST'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_TASK_HOURS_BY_BUSINESS = 'GET_TASK_HOURS_BY_BUSINESS'
export const UPDATE_TASK_HOURS_DATE = 'UPDATE_TASK_HOURS_DATE'
export const UPDATE_TASK_HOURS = 'UPDATE_TASK_HOURS'
export const GET_PROJECT_Error = 'GET_PROJECT_Error'
export const BUSINESS_ERROR = 'BUSINESS_ERROR'
export const GET_TASK_HOURS_BY_BUSINESS_BY_FOUNDER = 'GET_TASK_HOURS_BY_BUSINESS_BY_FOUNDER'
export const CREATE_TASK_AND_TASK_HOURS = 'CREATE_TASK_AND_TASK_HOURS'
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS'
export const GET_PROJECT_LIST_AND_APPEND = 'GET_PROJECT_LIST_AND_APPEND'
export const GET_BUSINESS_DETAILS = 'GET_BUSINESS_DETAILS'
export const CREATE_BUSINESS_DETAILS = 'GET_BUSINESS_DETAILS'
export const UPDATE_BUSINESS_DETAILS = 'GET_BUSINESS_DETAILS'
// Files
export const CREATE_FILE = 'CREATE_FILE'

// Misc
export const LOAD_STATE = 'LOAD_STATE'
export const SUCCESS = 'SUCCESS'

export const SUBMIT_PROJECT_WIZARD_DETAILS = 'SUBMIT_PROJECT_WIZARD_DETAILS';
export const SUBMIT_PROJECT_WIZARD_DETAILS_ERROR = 'SUBMIT_PROJECT_WIZARD_DETAILS_ERROR';
export const SUBMIT_PROJECT_WIZARD_DETAILS_SUCCESS = 'SUBMIT_PROJECT_WIZARD_DETAILS_SUCCESS';
export const UPDATE_WIZARD_SUBMISSION = "UPDATE_WIZARD_SUBMISSION";

export const SET_IS_BUSINESS_FIELD_SUBMITTED = 'SET_IS_BUSINESS_FIELD_SUBMITTED';
export const RESET_IS_BUSINESS_FIELD_SUBMITTED = 'RESET_IS_BUSINESS_FIELD_SUBMITTED';