export const GET_LIST_ENTRIES = 'GET_LIST_ENTRIES';
export const GET_LIST_ENTRIES_SUCCESS = 'GET_LIST_ENTRIES_SUCCESS';
export const GET_LIST_ENTRIES_ERROR = 'GET_LIST_ENTRIES_ERROR';

export const CREATE_LIST_ENTRY = 'CREATE_LIST_ENTRY';
export const EDIT_LIST_ENTRY = 'EDIT_LIST_ENTRY';
export const DELETE_LIST_ENTRY = 'DELETE_LIST_ENTRY';

export const GET_USERS_LIST_BY_USER_ID = 'GET_USERS_LIST_BY_USER_ID';
export const GET_USERS_LIST_BY_USER_ID_SUCCESS = 'GET_USERS_LIST_BY_USER_ID_SUCCESS';
export const GET_USERS_LIST_BY_USER_ID_ERROR = 'GET_USERS_LIST_BY_USER_ID_ERROR';

export const GET_LIST_ENTRIES_BY_ID = 'GET_LIST_ENTRIES_BY_ID';
export const GET_LIST_ENTRIES_BY_ID_SUCCESS = 'GET_LIST_ENTRIES_BY_ID_SUCCESS';
export const GET_LIST_ENTRIES_BY_ID_ERROR = 'GET_LIST_ENTRIES_BY_ID_ERROR';

export const GET_TEAM_MEMBER_LIST = 'GET_TEAM_MEMBER_LIST';
export const GET_TEAM_MEMBER_LIST_SUCCESS = 'GET_TEAM_MEMBER_LIST_SUCCESS';
export const GET_TEAM_MEMBER_LIST_ERROR = 'GET_TEAM_MEMBER_LIST_ERROR';


export const CREATE_RECENTLY_VIEWED_LIST = 'CREATE_RECENTLY_VIEWED_LIST';
export const CREATE_RECENTLY_VIEWED_LIST_SUCCESS = 'CREATE_RECENTLY_VIEWED_LIST_SUCCESS';
export const CREATE_RECENTLY_VIEWED_LIST_ERROR = 'CREATE_RECENTLY_VIEWED_LIST_ERROR';

export const GET_RECENTLY_VIEWED_LIST = 'GET_RECENTLY_VIEWED_LIST';
export const GET_RECENTLY_VIEWED_LIST_SUCCESS = 'GET_RECENTLY_VIEWED_LIST_SUCCESS';
export const GET_RECENTLY_VIEWED_LIST_ERROR = 'GET_RECENTLY_VIEWED_LIST_ERROR';

export const ON_UPDATE_LIST = 'ON_UPDATE_LIST';