const TODO_STATUS = 'Todo'
const IN_PROGRESS = 'In Progress'
const DONE = 'Done'
const DOING = 'Doing'

const TASK_STATUS = [TODO_STATUS, IN_PROGRESS, DONE, DOING]

const PAID_STATUS = 'paid'
const APPROVED_STATUS = 'approved'
const REPORTED_STATUS = 'reported'
const ACTIVE_STATUS = 'active'
const ARCHIVED_STATUS = 'archived'
const PENDING_STATUS = 'pending'

const LOWESET_PRIORITY = 'lowest'
const LOW_PRIORITY = 'low'
const MEDIUM_PRIORITY = 'medium'
const HIGH_PRIORITY = 'high'
const HIGHEST_PRIORITY = 'highest'

const FIXED_BUDGET = 'Fixed Price'
const HOURLY_RATE = 'Hourly Rate'

const SHORT_TERM_PROJECT = 'Short Term Business'
const LONG_TERM_PROJECT = 'Long Term Collaboration'

const BUDGET_TYPE = [FIXED_BUDGET, HOURLY_RATE]
const PROJECT_TYPE = [SHORT_TERM_PROJECT, LONG_TERM_PROJECT]

const TASK_PRIORITY = [LOWESET_PRIORITY, LOW_PRIORITY, MEDIUM_PRIORITY, HIGH_PRIORITY, HIGHEST_PRIORITY]
const INVOICE_STATUS = [PENDING_STATUS, PAID_STATUS, APPROVED_STATUS, REPORTED_STATUS, ACTIVE_STATUS, ARCHIVED_STATUS]

module.exports = {
  TODO_STATUS,
  IN_PROGRESS,
  BUDGET_TYPE,
  FIXED_BUDGET,
  HOURLY_RATE,
  PROJECT_TYPE,
  SHORT_TERM_PROJECT,
  LONG_TERM_PROJECT,
  DONE,
  DOING,
  TASK_STATUS,
  LOWESET_PRIORITY,
  LOW_PRIORITY,
  MEDIUM_PRIORITY,
  HIGH_PRIORITY,
  HIGHEST_PRIORITY,
  TASK_PRIORITY,
  INVOICE_STATUS,
  APPROVED_STATUS,
  PAID_STATUS,
  REPORTED_STATUS,
  ACTIVE_STATUS,
  ARCHIVED_STATUS,
  PENDING_STATUS
}
