const TODO_STATUS = 'todo'
const IN_PROGRESS = 'inprogress'
const DONE = 'done'
const DOING = 'doing'

const TASK_STATUS = [TODO_STATUS, IN_PROGRESS, DONE, DOING]

const PAID_STATUS = 'paid'
const APPROVED_STATUS = 'approved'
const REPORTED_STATUS = 'reported'
const ACTIVE_STATUS = 'active'
const ARCHIVED_STATUS = 'archived'

const LOWESET_PRIORITY = 'lowest'
const LOW_PRIORITY = 'low'
const MEDIUM_PRIORITY = 'medium'
const HIGH_PRIORITY = 'high'
const HIGHEST_PRIORITY = 'highest'

const TASK_PRIORITY = [LOWESET_PRIORITY, LOW_PRIORITY, MEDIUM_PRIORITY, HIGH_PRIORITY, HIGHEST_PRIORITY]
const INVOICE_STATUS = [PAID_STATUS, APPROVED_STATUS, REPORTED_STATUS, ACTIVE_STATUS, ARCHIVED_STATUS]

module.exports = {
  TODO_STATUS,
  IN_PROGRESS,
  DONE,
  DOING,
  TASK_STATUS,
  LOWESET_PRIORITY,
  LOW_PRIORITY,
  MEDIUM_PRIORITY,
  HIGH_PRIORITY,
  HIGHEST_PRIORITY,
  TASK_PRIORITY,
  INVOICE_STATUS,
  APPROVED_STATUS,
  PAID_STATUS,
  REPORTED_STATUS,
  ACTIVE_STATUS,
  ARCHIVED_STATUS
}
