export const CREATE_USER_LIST = 'CREATE_USER_LIST';
export const CREATE_USER_LIST_SUCCESS = 'CREATE_USER_LIST_SUCCESS';
export const CREATE_USER_LIST_ERROR = 'CREATE_USER_LIST_ERROR';

export const EDIT_USER_LIST = 'EDIT_USER_LIST';
export const EDIT_USER_LIST_SUCCESS = 'EDIT_USER_LIST_SUCCESS';
export const EDIT_USER_LIST_ERROR = 'EDIT_USER_LIST_ERROR';

export const DELETE_USER_LIST = 'DELETE_USER_LIST';
export const DELETE_USER_LIST_SUCCESS = 'DELETE_USER_LIST_SUCCESS';
export const DELETE_USER_LIST_ERROR = 'DELETE_USER_LIST_ERROR';