name: Deploy to Heroku Dev

on:
  push:
    branches:
      - main # Set your branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      run: docker login --username=_ --password=${{ secrets.HEROKU_API_TOKEN }} registry.heroku.com

    - name: Build and Push Docker Image
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Deploy to Heroku
      run: |
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
